### ISSUE TITLE
请教你一个关于websocket的问题

### ISSUE THREAD

**Issue by AggiWang** [xfgryujk/blivedm#1]
对于这种弹幕
![image](https://user-images.githubusercontent.com/31286734/40834731-359a1624-65c4-11e8-9e82-a873e64a32b0.png)
需要send后服务器返回消息确认成功的，要怎么用websocket客户端取弹幕？

**Comment by xfgryujk** [comment]
没看懂

**Comment by AggiWang** [comment]
就是在websocket确立建立连接时客户端发送的第一条消息必须是认证消息，验证成功才可以继续发送message，上图中的第一条就是客户端发送的认证消息，从第3条开始后面的发送的message才是去请求返回弹幕的，但是这种形式的websocket客户端应该怎么写？

**Comment by xfgryujk** [comment]
await 发送认证
ensure_future(接收弹幕)
for循环 await 发送请求弹幕
