### ISSUE TITLE
cmd可能发生变化，包数据解析可能存在遗漏

### ISSUE THREAD

**Issue by QvQQ** [xfgryujk/blivedm#11]
经过几天的使用，发现通过ws发送过来的消息可能发生了变化。比如，用户进入直播间已经无法捕捉到`WELCOME`命令，转而成为了`INTERACT_WORD`。
而原先当直播间关注人数发生变化时，会产生`ROOM_REAL_TIME_MESSAGE_UPDATE`，现在已经无法接收到该命令（但是在网页端与手机app端，仍然可以观察到**xxx关注了直播间**这样的消息），所以包数据的解析可能存在遗漏。

**Comment by xfgryujk** [comment]
理论上这个库只提供弹幕、礼物、舰长、SC，其他的消息处理自己写

**Comment by QvQQ** [comment]
是的，其他的消息处理我是自己写了。但**xxx关注了直播间**这样的消息既未当作“未知命令”写到log里，也未当作“未知包类型”写到log里，所以怀疑是否是包数据的解析遗漏了……

**Comment by xfgryujk** [comment]
`ROOM_REAL_TIME_MESSAGE_UPDATE`在“其他已知命令”里

**Comment by QvQQ** [comment]
不好意思……忘记说明了。
我看到您代码的处理方式是，“其他已知命令”在`_COMMAND_HANDLERS`中被设为None，因而不被处理。而我已经注释掉该语句（相当于将所有`其他已知命令”当作未知命令），如果有任何其他的cmd的话，都应该打到log里。可是仍然无法捕获到有关关注人数变动的消息。所以才有上述的疑问。

**Comment by xfgryujk** [comment]
刚试的可以接收到
```python
    async def __on_real_time_message_update(self, command):
        print(command)
    _COMMAND_HANDLERS['ROOM_REAL_TIME_MESSAGE_UPDATE'] = __on_real_time_message_update  # 关注人数变化
```
```python
{'cmd': 'ROOM_REAL_TIME_MESSAGE_UPDATE', 'data': {'roomid': 14052636, 'fans': 152433, 'red_notice': -1, 'fans_club': 2001}}
{'cmd': 'ROOM_REAL_TIME_MESSAGE_UPDATE', 'data': {'roomid': 14052636, 'fans': 152436, 'red_notice': -1, 'fans_club': 2001}}
```

**Comment by QvQQ** [comment]
woc🤣，我去试试

**Comment by xfgryujk** [comment]
https://github.com/xfgryujk/blivedm/blob/6618bf5c484cbe5a6f7e32f8e5d65ed0b74849c7/blivedm.py#L641
只有第一次接收到未知命令才会打log，不然每次都打太多了

**Comment by QvQQ** [comment]
明白了，应该是B站修改了机制，使得粉丝数微量增加的时候（比如我的直播间🤣）并不会推送`ROOM_REAL_TIME_MESSAGE_UPDATE`。
可以访问`https://api.bilibili.com/x/relation/stat?vmid=372984197`一边刷新一边看hhh

**Comment by worm128** [comment]
INTERACT_WORD 进入直播间的事件我捕获不了，你们都可以吗？
