### ISSUE TITLE
ssl问题

### ISSUE THREAD

**Issue by yjqiang** [xfgryujk/blivedm#2]
class 'ssl.SSLError'> [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:749)

这个很诡异 因为电脑上的chrome正常使用  但是脚本运行就ssl错误，试了好几个电脑了

**Comment by xfgryujk** [comment]
```python
import ssl
ssl._create_default_https_context = ssl._create_unverified_context
```

**Comment by yjqiang** [comment]
讲道理 chrome的ssl证书是系统的……但是chrome那里不报错啊……  不清楚证书出了什么问题

**Comment by xfgryujk** [comment]
那大概是Python有自己的证书储存

**Comment by yjqiang** [comment]
https://github.com/aaugustin/websockets/issues/419

**Comment by xfgryujk** [comment]
我平时用的

```
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

在`python\Library\ssl`下有证书`cacert.pem`，验证没问题

我特地去官网下的

```
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:04:45) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
```

python目录下找不到证书，验证也失败了

肯定是你编译Python时没加上OpenSSL。实在解决不了就用上面的方法取消验证呗

**Comment by xfgryujk** [comment]
不好意思之前的方法只能用于https，已经编辑成可以用于wss的了

**Comment by yjqiang** [comment]
ssl这里的确有问题 而且应该是b站锅
https://github.com/aaugustin/websockets/issues/419
"openssl s_client -showcerts -connect broadcastlv.chat.bilibili.com:2245 </dev/null says that the certificate for that server isn't trusted by my system."

**Comment by xfgryujk** [comment]
嗯，我试了一下Anaconda版的也不行了，之前还好好的
看了下源码，Python的ssl是可以正确加载系统证书的

**Comment by yjqiang** [comment]
基本就是b站的锅了mmp
