### ISSUE TITLE
ssl处理逻辑

### ISSUE THREAD

**Issue by yjqiang** [xfgryujk/blivedm#3]
忽略ssl证书是一种不安全的行为，所以还不如抛弃ssl，使用2244接口

**Comment by xfgryujk** [comment]
讲道理谁没事嗅探你和B站弹幕的通信

**Comment by yjqiang** [comment]
wss网页上会传输cookie等信息，所以。。。还是遵守原逻辑吧

**Comment by xfgryujk** [comment]
这个项目又没有用到登录信息，要用到时自己改就行
