### ISSUE TITLE
前几天B站抽风以后用户名会变成类似“A***”的格式

### ISSUE THREAD

**Issue by GYZBurNing** [xfgryujk/blivedm#31]
前几天B站抽风以后，刚开始获取弹幕的时候能正常显示用户名，过一段时间就变成第一个字＋***，类似下图。大佬能修复下吗，求求了
!
[无标题](https://github.com/xfgryujk/blivedm/assets/45756339/77588efe-2338-4140-b08a-86236e7a2b3f)

**Comment by xfgryujk** [comment]
修了

**Comment by GYZBurNing** [comment]
感谢大佬

**Comment by holwell** [comment]
> 修了

还得是你！
![02717445](https://github.com/xfgryujk/blivedm/assets/45387795/68600ac7-4df0-456e-ab75-aadb64f06a52)
么么(* ￣3)(ε￣ *)
