### ISSUE TITLE
弹幕丢失率很高

### ISSUE THREAD

**Issue by xqe2011** [xfgryujk/blivedm#33]
几乎无法接收到新弹幕，换了多个IP和携带ClientSession登陆态也无法解决。
版本 [28645d5](https://github.com/xfgryujk/blivedm/tree/28645d5e37fe4ba709c23116e66efebb0cc227f6)

**Comment by xfgryujk** [comment]
这个库不负责解决一次爬多个直播间的风控策略，自己想办法

**Comment by xqe2011** [comment]
谢谢你的回复，但我不是一次爬多个直播间，我测试的IP只打开了一个直播间

**Comment by xqe2011** [comment]
这个是今天开始的

**Comment by xfgryujk** [comment]
你测试一下是不是消息处理耗时太多了

**Comment by xqe2011** [comment]
消息处理函数只print也会这样，blivechat/blivedm都出现了相同的问题

**Comment by xqe2011** [comment]
我自己尝试更换了代码里的UA并无用，并不只是blivedm,其他使用[bilibili-api](https://github.com/Nemo2011/bilibili-api)的项目也出现了一样的问题，是B站是不是更新了什么认证包算法

**Comment by xfgryujk** [comment]
还真复现了，部分直播间没有登录时接收弹幕会被限流

**Comment by xqe2011** [comment]
我测试了如果携带uid+bvuid，然后使用浏览器访问接口获取Key合成认证包就能避免限流，目前尚未明确是获取Key接口携带什么Headers导致返回的key可能限流

**Comment by xqe2011** [comment]
提供一个临时修复方案，测试了一下基本没问题，修改所有UA，携带Cookie，携带UID，就应该可以解决

**Comment by xfgryujk** [comment]
好像uid不能乱填了，现在uid和token不匹配有可能被限流。填0就没被限流，并且能连上broadcastlv.chat.bilibili.com之外的服务器。但是填0会导致无法获取弹幕昵称和uid

**Comment by cnSchwarzer** [comment]
别多想了，老老实实登陆态了

**Comment by xfgryujk** [comment]
添加了使用cookie连接的方法演示。后续会加上开放平台接口

**Comment by cnSchwarzer** [comment]
> 添加了使用cookie连接的方法演示。后续会加上开放平台接口

开放平台是不是必须要code了啊，v1的那个我请求就是应用无效

**Comment by xqe2011** [comment]
开放平台不是需要AK和SK吗

**Comment by z0z0r4** [comment]
开放平台可还行，有门槛的吧我记得

建议老实登录，和反爬斗没意义，没性价比

**Comment by Akegarasu** [comment]
经测试，如果token不是携带cookie获取的，只在enter packet携带buvid仍然丢失率很高。还有测试疑似和不同的弹幕服务器有关，broadcastlv比较严格

**Comment by xfgryujk** [comment]
> 经测试，如果token不是携带cookie获取的，只在enter packet携带buvid仍然丢失率很高。还有测试疑似和不同的弹幕服务器有关，broadcastlv比较严格

其他服务器uid和token不匹配大概率就断开连接了

**Comment by xfgryujk** [comment]
接口差不多就改成这样了，目前没条件测试，有人帮忙测试吗

**Comment by why0209** [comment]
> 接口差不多就改成这样了，目前没条件测试，有人帮忙测试吗

单个很稳定，如果量大的话还是存在收不到弹幕的现象

**Comment by cnSchwarzer** [comment]
有没有人测试下同一个Cookie连接大量不同房间，以及同一个Cookie多次连接相同房间，是否会造成其他连接被中断掉呀

**Comment by why0209** [comment]
> 有没有人测试下同一个Cookie连接大量不同房间，以及同一个Cookie多次连接相同房间，是否会造成其他连接被中断掉呀

我是第一种

**Comment by xfgryujk** [comment]
> > 接口差不多就改成这样了，目前没条件测试，有人帮忙测试吗
> 
> 单个很稳定，如果量大的话还是存在收不到弹幕的现象

不是，我想测的是开放平台接口

**Comment by why0209** [comment]
> > > 接口差不多就改成这样了，目前没条件测试，有人帮忙测试吗
> > 
> > 单个很稳定，如果量大的话还是存在收不到弹幕的现象
> 
> 不是，我想测的是开放平台接口

呜呜 没有key

**Comment by c-basalt** [comment]
那个开放平台好像只开放给企业申请吧，文档里直接说的“暂未开通个人开发者的申请入驻”，感觉大部分主播估计很难用的上

**Comment by xfgryujk** [comment]
> 那个开放平台好像只开放给企业申请吧，文档里直接说的“暂未开通个人开发者的申请入驻”，感觉大部分主播估计很难用的上 是计划会内置一个appkey之类的吗

现在个人可以申请了，我已经通过了。blivechat的话应该做成没有key的时候把请求转发到我的服务器

**Comment by why0209** [comment]
> > 那个开放平台好像只开放给企业申请吧，文档里直接说的“暂未开通个人开发者的申请入驻”，感觉大部分主播估计很难用的上 是计划会内置一个appkey之类的吗
> 
> 现在个人可以申请了，我已经通过了。blivechat的话应该做成没有key的时候把请求转发到我的服务器

大佬，直接创建项目不创建开发版本的话appid可以供多人使用吗

**Comment by xfgryujk** [comment]
> > > 那个开放平台好像只开放给企业申请吧，文档里直接说的“暂未开通个人开发者的申请入驻”，感觉大部分主播估计很难用的上 是计划会内置一个appkey之类的吗
> > 
> > 
> > 现在个人可以申请了，我已经通过了。blivechat的话应该做成没有key的时候把请求转发到我的服务器
> 
> 大佬，直接创建项目不创建开发版本的话appid可以供多人使用吗

没上线的项目只能用在自己的直播间

**Comment by falcomzwei** [comment]
> at

请问要怎么申请？注册页面看起来只限企业

**Comment by falcomzwei** [comment]
> > 那个开放平台好像只开放给企业申请吧，文档里直接说的“暂未开通个人开发者的申请入驻”，感觉大部分主播估计很难用的上 是计划会内置一个appkey之类的吗
> 
> 现在个人可以申请了，我已经通过了。blivechat的话应该做成没有key的时候把请求转发到我的服务器

请问要怎么申请，页面上看还是只有企业可以注册

**Comment by xfgryujk** [comment]
> > > 那个开放平台好像只开放给企业申请吧，文档里直接说的“暂未开通个人开发者的申请入驻”，感觉大部分主播估计很难用的上 是计划会内置一个appkey之类的吗
> > 
> > 
> > 现在个人可以申请了，我已经通过了。blivechat的话应该做成没有key的时候把请求转发到我的服务器
> 
> 请问要怎么申请，页面上看还是只有企业可以注册

Read The ~~Fucking~~ Fine Documentation: https://open-live.bilibili.com/document/849b924b-b421-8586-3e5e-765a72ec3840
