### ISSUE TITLE
真的有人收到过GUARD_BUY消息吗

### ISSUE THREAD

**Issue by cnSchwarzer** [xfgryujk/blivedm#36]
从来没收到过，一直都是USER_TOAST_MSG

**Comment by xfgryujk** [comment]
两个消息都有，网页显示用的是USER_TOAST_MSG，我懒得改了

**Comment by cnSchwarzer** [comment]
> 两个消息都有，网页显示用的是USER_TOAST_MSG，我懒得改了

是鉴权时那个 platform 区分吗，GUARD_BUY是哪个平台的呀

**Comment by xfgryujk** [comment]
> > 两个消息都有，网页显示用的是USER_TOAST_MSG，我懒得改了
> 
> 是鉴权时那个 platform 区分吗，GUARD_BUY是哪个平台的呀

web的，没试过其他平台
