### ISSUE TITLE
 加了cookie还是未登陆状态

### ISSUE THREAD

**Issue by kavencat** [xfgryujk/blivedm#38]
![image](https://github.com/xfgryujk/blivedm/assets/99724336/9e5b5e26-fdd0-433a-b8d4-7e7dbe7475ce)

**Comment by xfgryujk** [comment]
让你填的是SESSDATA，不是所有cookie

**Comment by jokerElsa** [comment]
https://github.com/BilibiliVideoDownload/BilibiliVideoDownload/wiki/%E8%8E%B7%E5%8F%96SESSDATA
附上个如何获取sessdata，我开始也去找怎么获取cookie了

**Comment by c-basalt** [comment]
好像弹幕服务器又改回去了？
