### ISSUE TITLE
项目还更新么？

### ISSUE THREAD

**Issue by yjqiang** [xfgryujk/blivedm#4]
非常感谢此项目带来的帮助。我在本项目基础上，得以做了很多事情。现在我把websocket封装了起来。但是不太想单独做一个项目了。所以就考虑重新反馈到你这里。所以想问一下你这里还更新么

**Comment by xfgryujk** [comment]
我觉得该有的功能都有了，要加的话自己改吧...

**Comment by yjqiang** [comment]
> 我觉得该有的功能都有了，要加的话自己改吧...

不接受pull请求了么？

**Comment by xfgryujk** [comment]
接受

**Comment by yjqiang** [comment]
> 接受

我稍微说一下我做的工作
1.aiohttp与websocket模块相比，session的引入可以提高效率，而且aiohttp是个很庞大的模块，不会出现跑路情况，感觉质量不错。于是我用了aiohttp
2.断线重连这里我处理了一下，while sleep太恶心了点
3.加入了reset roomid功能，可以在运行过程中重设房间并自动断开老的连接并连接新房间

**Comment by yjqiang** [comment]
https://github.com/yjqiang/bili2.0/blob/master/danmu.py
可能我要弄的话就基本全部改了。你如果接受的话，我修改一下就合并过来

**Comment by xfgryujk** [comment]
你先提交吧我还可以改

**Comment by yjqiang** [comment]
> 你先提交吧我还可以改

行  要等一会儿  要不你给我个权限吧 我直接提交过去 我现在代码在ipad上  fork再折腾麻烦

**Comment by xfgryujk** [comment]
你交PR我才能审核啊...
