### ISSUE TITLE
2023-11-14 配置SESSDATA后仍然无法获取用户昵称

### ISSUE THREAD

**Issue by Ikaros-521** [xfgryujk/blivedm#42]
看着值好像变长了，阿b又改了

**Comment by xfgryujk** [comment]
没有复现

**Comment by Ikaros-521** [comment]
> 没有复现

啊 回头我再试试

**Comment by Ikaros-521** [comment]
确实，又行了...

**Comment by watchpoints** [comment]
[[发布到专栏](https://github.com/BilibiliVideoDownload/BilibiliVideoDownload/wiki/%E8%8E%B7%E5%8F%96SESSDATA)](https://github.com/xfgryujk/blivedm/issues/38)

**Comment by xuan06zyx** [comment]
![QQ_1725850978314](https://github.com/user-attachments/assets/b6502467-4dea-457e-a8ae-b445cf82f7ed)
似乎sessdata变得更长了，使用示例代码填入sessdata运行也无法获取完整的用户名
