### ISSUE TITLE
Python 3.12 can't build wheels for aiohttp and yarl

### ISSUE THREAD

**Issue by hydrotho** [xfgryujk/blivedm#44]
Python 3.12 无法安装 `aiohttp`，官方已经发布 3.9.0 版本修复此问题，需要更新 `requirements.txt`：

```
aiohttp==3.8.6
↓
aiohttp==3.9.0
```

详见：

- https://github.com/aio-libs/aiohttp/issues/7739
- https://github.com/aio-libs/aiohttp/pull/7302
- https://github.com/aio-libs/aiohttp/releases/tag/v3.9.0

**Comment by hydrotho** [comment]
此外，`yarl` 也无法安装，需要更新 `requirements.txt`：

```
yarl==1.8.2
↓
yarl==1.9.2
```

**Comment by xfgryujk** [comment]
你们怎么敢用修订号为0的最新版本的
