### ISSUE TITLE
您好，sample.py获取不到点赞数量

### ISSUE THREAD

**Issue by txunda** [xfgryujk/blivedm#52]
您好，sample.py获取不到点赞数量呢，{"contribution_info": {"grade": 0}, "dmscore": 32, "fans_medal": {"anchor_roomid": 0, "guard_level": 0, "icon_id": 0, "is_lighted": 0, "medal_color": 0, "medal_color_border": 0, "medal_color_end": 0, "medal_color_start": 0, "medal_level": 0, "medal_name": "", "score": 0, "special": "", "target_id": 0}, "group_medal": null, "identities": [1], "is_mystery": false, "like_icon": "https://i0.hdslb.com/bfs/live/23678e3d90402bea6a65251b3e728044c21b1f0f.png", "like_text": "\u4e3a\u4e3b\u64ad\u70b9\u8d5e\u4e86", "msg_type": 6, "show_area": 0, "uid": 514456342, "uinfo": {"base": {"face": "https://i0.hdslb.com/bfs/face/8c8feab3c2b8ee2a7d298be98d295d36586c84a2.jpg", "is_mystery": false, "name": "bili_181425436453", "name_color": 0, "name_color_str": "", "official_info": {"desc": "", "role": 0, "title": "", "type": -1}, "origin_info": {"face": "https://i0.hdslb.com/bfs/face/8c8feab3c2b8ee2a7d298be98d295d36586c84a2.jpg", "name": "bili_181425436453"}, "risk_ctrl_info": null}, "guard": {"expired_str": "", "level": 0}, "guard_leader": null, "medal": null, "title": null, "uhead_frame": null, "uid": 514456342, "wealth": null}, "uname": "bili_181425436453", "uname_color": ""}

**Comment by xfgryujk** [comment]
sample.py里面有点赞消息的处理吗

**Comment by txunda** [comment]
有的，能打印出来点赞的用户信息，您看上面的数据里有like_text，但是没有like_count这个字段

**Comment by txunda** [comment]
<img width="885" alt="image" src="https://github.com/xfgryujk/blivedm/assets/76721805/dc19e491-5977-4438-bee0-3c03f33f3844">
<img width="752" alt="image" src="https://github.com/xfgryujk/blivedm/assets/76721805/6afc6720-7a6a-451e-8c9e-79f6e10bbc8e">

**Comment by txunda** [comment]
大佬，这个是我参考您open_live那个加的，我现在就是想获取到用户的点赞数量，您看看有啥好的方法吗

**Comment by xfgryujk** [comment]
自己逆向
