### ISSUE TITLE
支持 PEP 517 打包

### ISSUE THREAD

**Issue by mokurin000** [xfgryujk/blivedm#59]
动因：
- 可以上传到 Pypi（目前被第三者同名上传）
- 更便于被指定为依赖 （blivechat使用git submodule管理该依赖）
- 统一的依赖安装方式（同上一条）
- 允许装入 site packages
- 可使用绝对路径模块引用

继 #57 错误思路重开

**Comment by mokurin000** [comment]
有任何更新吗

**Comment by xfgryujk** [comment]
等我有空了看看吧
