### ISSUE TITLE
问下有办法获取到发弹幕的用户是否为房管的标识吗

### ISSUE THREAD

**Issue by 2-3-5-7** [xfgryujk/blivedm#61]
类似下图，比如一个 `isadmin` 字段之类的
![image](https://github.com/user-attachments/assets/2d5e8bee-1537-4517-a04c-84c0273216c8)

**Comment by xfgryujk** [comment]
https://github.com/xfgryujk/blivedm/blob/defcc7ad58066d053a6653d43d3c31078c655c1b/blivedm/models/web.py#L70
