### ISSUE TITLE
如何过滤掉这种warning信息，我尝试添加了过滤器但是没有成功，另外填写了cookie的信息也无法获取uid和用户名

### ISSUE THREAD

**Issue by TilapiaLog** [xfgryujk/blivedm#63]
如issue，因为github手机端的问题我无法上传图片，我所提的warning信息大概是由unknown cmd导致的

**Comment by xfgryujk** [comment]
https://docs.python.org/3/library/logging.html#filter-objects

**Comment by xfgryujk** [comment]
填cookie我试了可以获取用户名
