### ISSUE TITLE
请教一下怎么获取user toast的内容

### ISSUE THREAD

**Issue by u2shana** [xfgryujk/blivedm#66]
想收集弹幕统计舰长，但是message返回的金额是未打折的金额。
我看blrec录制的弹幕会多录一行toast，里面的是实际的金额，还包括用户的上舰天数的系统提醒等
<toast ts="XXX" uid="XXX" user="XXX" unit="月" count="1" price="138000" role="舰长" level="3" XXX续费了舰长，今天是TA陪伴主播的第XXX天/toast>

99%gpt编程，所以不知道如何获取，请教一下

**Comment by xfgryujk** [comment]
有另一条上舰的消息`USER_TOAST`，信息多一些，但我没有处理，你可以自己处理

**Comment by u2shana** [comment]
> 有另一条上舰的消息`USER_TOAST_MSG`，信息多一些，但我没有处理，你可以自己处理

就是在不知道怎么捕获处理USER_TOAST_MSG，本来上舰的人就难找，根本不知道dict返回究竟长啥样
