### ISSUE TITLE
几个小细节

### ISSUE THREAD

**Issue by yjqiang** [xfgryujk/blivedm#8]
1. https://github.com/xfgryujk/blivedm/blob/master/blivedm.py#L387 这里需要加一个 timeout，否则可能在网络 GG 的时候没什么提示就凉了，完全无法感知。由于心跳的机制，这个时间限制可以是 30 秒左右。
1. 主协程这里其实很奇怪，心跳等可能也会发生失败等，这时也需要自己监控到并且重启。你这样把接收写在[主协程](https://github.com/xfgryujk/blivedm/blob/master/blivedm.py#L387)，可能还是无法及时感知网络断开等问题。

**Comment by xfgryujk** [comment]
心跳包发送失败的话读取的地方也会出错吧

**Comment by yjqiang** [comment]
> 心跳包发送失败的话读取的地方也会出错吧

心跳发送有timeout，你如果卡在timeout了怎么办

**Comment by xfgryujk** [comment]
发送超时了就重连啊

**Comment by yjqiang** [comment]
那你的超时呢？在哪里？等一个几分钟的最终超时么？

**Comment by xfgryujk** [comment]
那是TCP的事，一段时间服务器没有ACK就判定连接断开了

**Comment by yjqiang** [comment]
你这是ws啊？tcp超时还有重连机制，ws比tcp高一层，应该也有自己的措施吧

**Comment by xfgryujk** [comment]
要不你做个实验发现心跳机制没检测到断线再来通知我？

**Comment by yjqiang** [comment]
我有碰到啊。。。超时30秒没有检测到，然后timeout返回了

**Comment by xfgryujk** [comment]
我试了一下，加入房间后断掉上游链路，心跳包发送后大约10秒主协程出错，但是奇怪的是2个except分支都不走直接走finally分支了...所以实际上还是重连了只是没有输出日志

**Comment by yjqiang** [comment]
你把网断掉的话，心跳可能正好刚刚发完，这时候你再加上一个发送的timeout，断线检测会很迟钝。

**Comment by yjqiang** [comment]
反正我的逻辑已经可以达到几k连接量坚持几天不会有异常了，我的分支基本与你的已经没关系了。。。

**Comment by xfgryujk** [comment]
懂了，断网时for message循环会结束
