### ISSUE TITLE
关于版权问题

### ISSUE THREAD

**Issue by yjqiang** [xfgryujk/blivedm#9]
https://github.com/yjqiang/danmu
这份代码是 fork 自本项目，但我最近有计划将其打包至 pypi。
[license](https://github.com/yjqiang/danmu/blob/master/LICENSE) 显示为你的名字我还没改，但是你可以看到基本上这份代码与你的代码没有什么关系了，如果不修改 license 应该很奇怪吧，pypi 里面作者是我， 许可名字却是你。
所以想问一下，如果我打包的话，可否把[版权时间 Copyright (c) 2018 xfgryujk](https://github.com/yjqiang/danmu/blob/master/LICENSE#L3) 这里，fork你的时间之前，代码版权归你，之后到现在，版权归我。

**Comment by xfgryujk** [comment]
为什么不新建一个库呢

**Comment by yjqiang** [comment]
> 为什么不新建一个库呢

懒…

**Comment by yjqiang** [comment]
https://blog.walterlv.com/post/how-to-detach-the-fork-in-github.html
或者这样么

**Comment by xfgryujk** [comment]
你切断然后改协议吧

**Comment by yjqiang** [comment]
非常感谢，我还是把协议按时间吧，毕竟最初是从你那里 fork 的。就是保留原来的 copyright，再加上 2020 年我自己。
